1. WRITE A QUERY TO DISPLAY TOTAL SALARY NEEDED TO PAY EACH
JOB IN EMPLOYEE TABLE.
SQL> SELECT SUM(SAL)
  2  FROM EMP
  3  GROUP BY JOB;
--------------------------------------------------------------------
2. WRITE A QUERY TO DISPLAY THE HIRE DATE ON WHICH AT LEAST 3
EMPLOYEES WHERE HIRED.
SQL> SELECT HIREDATE,COUNT(HIREDATE)
  2  FROM EMP
  3  GROUP BY HIREDATE
  4  HAVING COUNT(HIREDATE)>=3;
--------------------------------------------------------------------
3. WRITE A QUERY TO DISPLAY THE DEPARTMENT NUMBER WHICH HAS
MORE THAN 2 EMPLOYEES AND THE TOTAL AMOUNT REQUIRED TO
PAY THE MONTHLY SALARIES OF ALL THE EMPLOYEES IN THAT
DEPARTMENT SHOULD BE MORE THAN 9000.
SQL> SELECT COUNT(*),DEPTNO
  2  FROM EMP
  3  GROUP BY DEPTNO
  4  HAVING COUNT(*)>2 AND SUM(SAL)>9000;
--------------------------------------------------------------------
4. WRITE A QUERY TO DISPLAY NUMBER OF EMPLOYEES WORKING IN
EACH DEPARTMENT AND ITS’ AVERAGE SALARY BY EXCLUDING ALL
THE EMPLOYEES WHOSE SALARY IS LESS THAN THEIR COMMISSION.
SQL>SELECT DEPTNO,COUNT(*),AVG(SAL) 
	2 FROM EMP 
	3 WHERE  SAL<COMM 
	4 GROUP BY DEPTNO;
--------------------------------------------------------------------
5. WRITE A QUERY TO DISPLAY THE SALARIES WHICH HAS REPETITIONS
IN THE SAL COLUMN OF EMPLOYEE TABLE.
SQL> SELECT SAL,COUNT(*)-1
  2  FROM EMP
  3  GROUP BY SAL;
--------------------------------------------------------------------
6. WRITE A QUERY TO DISPLAY THE EMPLOYEE NAME ONLY IF MORE
THAN ONE PERSON IN THE EMPLOYEES OF THE COMPANY HAS SAME
NAME.
SQL> SELECT ENAME,COUNT(*)-1
  2  FROM EMP
  3  GROUP BY ENAME;
--------------------------------------------------------------------
7. WRITE A QUERY TO DISPLAY THE DEPARTMENT NUMBER WHOSE
AVERAGE SALARY IS BETWEEN 2500 AND 3000.
SQL> SELECT DEPTNO 
   2 FROM EMP 
   3 GROUP BY DEPTNO 
   4 HAVING AVG(SAL) BETWEEN 2500 AND 3000;
--------------------------------------------------------------------
8. WRITE A QUERY TO DISPLAY THE NUMBER OF EMPLOYEES ONLY IF
THEY ARE WORKING AS MANAGER OR ANALYST AND THEIR ANNUAL
SAL SHOULD END WITH A ZERO, IN EACH DEPARTMENT.
SQL> SELECT COUNT(*),DEPTNO
  2  FROM EMP
  3  WHERE JOB IN ('MANAGER','ANALYST') AND SAL*12 LIKE '%0' GROUP BY DEPTNO;
--------------------------------------------------------------------
9. WRITE A QUERY TO DISPLAY NO OF CLERKS WORKING IN EACH DEPARTMENT.
SQL> SELECT COUNT(*)
  2  FROM EMP
  3  WHERE JOB IN 'CLERK'
  4  GROUP BY DEPTNO;
--------------------------------------------------------------------
10. WRITE A QUERY TO DISPLAY HIGHEST SALARY GIVEN TO A MANAGER IN EACH DEPARTMENT.
SQL> SELECT MAX(SAL)
  2  FROM EMP
  3  WHERE JOB IN 'MANAGER'
  4  GROUP BY DEPTNO;
--------------------------------------------------------------------
11. WRITE A QUERY TO DISPLAY NO OF TIMES THE SALARIES HAVE
REPEATED IN THE EMP TABLE.
SQL> SELECT COUNT(*)-1,SAL
  2  FROM EMP
  3  GROUP BY SAL;
--------------------------------------------------------------------
12.WRITE A QUERY TO DISPLAY DEPTNO AND NUNBER OF EMPLOYEES
WHORKING IN EACH DEPARTMENT EXCEPT FOR THOSE WORKING IN DEPT 10
SQL>SELECT COUNT(*),DEPTNO 
  2	FROM EMP  
  3 WHERE DEPTNO NOT IN(10) 
  4 GROUP BY DEPTNO;
--------------------------------------------------------------------
13.WAQTD NUMBER OF EMPLOYEES GETTING COMISSION IN EACH
DEPARTMENT
SQL> SELECT COUNT(*)
  2  FROM EMP
  3  WHERE COMM IS NOT NULL
  4  GROUP BY DEPTNO;
--------------------------------------------------------------------
14.WAQTD NUMBER OF EMPLOYEES GETTING SALARY MORE THAN 1600
EXCLUDING ALL THE MANAGERS IN EACH DEPARTEMNT
SQL> SELECT COUNT(*),DEPTNO
  2  FROM EMP
  3  WHERE SAL > 1600 AND JOB NOT IN 'MANAGER'
  4  GROUP BY DEPTNO;
--------------------------------------------------------------------
15.WAQTD AVERAGE SALARY NEEDED TO PAY ALL THE EMPLOYEES WHO
ARE HAVING A REPORTING MANAGER IN EACH JOB .
SQL> SELECT AVG(SAL)
  2  FROM EMP
  3  WHERE JOB IN 'MANAGER'
  4  GROUP BY JOB;
--------------------------------------------------------------------
16.WAQTD NUMBER OF EMPLOYEES HIRED INTO THE SAME DEPARTMENT
ON THE SAME DAY
SQL> SELECT COUNT(*)
  2  FROM EMP
  3  GROUP BY HIREDATE,DEPTNO;
--------------------------------------------------------------------
17.WAQTD NUMBER OF EMPLOYEES GETTING THE SAME SALARY ,
WORKING IN THE SAME DEPARTMENT
SQL> SELECT COUNT(*),SAL,DEPTNO
  2  FROM EMP
  3  GROUP BY SAL,DEPTNO;
--------------------------------------------------------------------
18.WAQTD MAXIMUM SALARY GIVEN IN EACH DESIGNATION EXCLUDING
THOSE WHOS NAME STARTS WITH ‘K’
SQL> SELECT MAX(SAL)
  2  FROM EMP
  3  WHERE ENAME NOT LIKE 'K%';
--------------------------------------------------------------------
19.WAQTD NUMBER OF EMPLOYEES REPORTING TO 7839 IN EACH DEPT
SQL> SELECT COUNT(*)
  2  FROM EMP
  3  WHERE MGR IN 7839
  4  GROUP BY DEPTNO;
--------------------------------------------------------------------
20.WAQTD NUMBER OF EMPLOYEE NAMES STARTING WITH AN VOWEL IN
EACH DEPARTMENT
SQL> SELECT COUNT(*),DEPTNO
  2  FROM EMP
  3  WHERE ENAME LIKE 'A%' OR ENAME LIKE 'E%' OR ENAME LIKE 'I%' OR ENAME LIKE 'O%' OR ENAME LIKE 'U%'
  4  GROUP BY DEPTNO;