1.WAQTD NUM OF EMP WORKING AS SALESMAN IN ACCOUNTING DEPT;
SQL> SELECT COUNT(*)
  2  FROM EMP
  3  WHERE JOB IN 'SALESMAN' AND DEPTNO=(SELECT DEPTNO FROM DEPT WHERE DNAME='ACCOUNTING');
--------------------------------------------------------------------
2.WAQTD TOTAL SAL GIVEN TO EMP WORKING IN DALLAS
SQL> SELECT SUM(SAL)
  2  FROM EMP
  3  WHERE DEPTNO=(SELECT DEPTNO FROM DEPT WHERE LOC IN 'DALLAS');
--------------------------------------------------------------------
3.WAQTD DETAILS OF EMP WHO ARE HIRED AFTER ADAMS AND EARNING LESS THAN KING
SQL> SELECT *
  2  FROM EMP
  3  WHERE HIREDATE>(SELECT HIREDATE FROM EMP WHERE ENAME IN 'ADAMS')
  4  AND SAL <(SELECT SAL FROM EMP WHERE ENAME='KING');
--------------------------------------------------------------------
4.WAQTD NAME OF EMP WHOSE LOC HAS CHAR S
SQL> SELECT ENAME
  2  FROM EMP
  3  WHERE DEPTNO IN (SELECT DEPTNO FROM DEPT WHERE LOC LIKE '%S%');
--------------------------------------------------------------------
5.WAQTD THE AVG SAL GIVEN TO AN EMP WHO WORKS SAME JOB AS WARD
SQL> SELECT AVG(SAL)
  2  FROM EMP
  3  WHERE JOB IN (SELECT JOB FROM EMP WHERE ENAME='WARD');
--------------------------------------------------------------------
6.WAQTD NAMES OF EMP WHO ARE MANAGERS IN SALES
SQL> SELECT ENAME
  2  FROM EMP
--------------------------------------------------------------------
7.WAQTD THE DEPT NAME OF EMP WHO ARE GETTING COMM
SQL> SELECT DNAME FROM DEPT
  2  WHERE DEPTNO IN (SELECT DEPTNO FROM EMP WHERE COMM IS NOT NULL);
--------------------------------------------------------------------
2.WAQTD NAME OF DEPT WHOSE EMP GETS SAL OF 1600/-
SQL> SELECT DNAME
  2  FROM DEPT
  3  WHERE DEPTNO IN (SELECT DEPTNO FROM EMP WHERE SAL=1600);
